### ISSUE TITLE
Add translations and cache

### ISSUE THREAD

**Issue by mattkanwisher** [VoxlyHq/retro_voice#2]
1) Add a new command line arg, that enables translations,
ex. --trans=en,jp <--- would translate English to Japanese 
feel free to name this or format this however, and it only does translations if this is on

2) Use OpenAI or something similar to do a translation 

3) Store the translation into a local file, and cache them, so we only make the calls once

4) Translations should show up in the video feed

**Comment by ShaneKoNaung** [comment]
Translation part is done. It works with retroarch window. 

8f81cb30dd998c416ad121f4ed648328a5dd5ae3

WIP - video source, video source + video stream,,  retroarch source + video stream,

**Comment by ShaneKoNaung** [comment]
https://github.com/VoxlyHq/retro_voice/assets/26071811/d4431f19-8412-45b3-ab03-c69e1d8feabb

**Comment by ShaneKoNaung** [comment]
Translation from video input is done with this commit. 

```
python ss.py -v video_file_path -trans en,jp
```

29990166e827691f66a9f0cca6f681589fcbf92a


https://github.com/VoxlyHq/retro_voice/assets/26071811/b9796303-02d1-4850-bbd5-12cc9282ce3f

**Comment by ShaneKoNaung** [comment]
Translation from retroarch window with videostream is done with this commit.

```
python ss.py -is -trans en,jp
```

6f8d616cecdd94223c21ef6f77596750ecc13bd6


https://github.com/VoxlyHq/retro_voice/assets/26071811/536d8f3a-1a9c-471c-b9e6-d67cc615b2c6
